-- Supabase Dashboard > SQL Editor içinde çalıştırın.
create table if not exists public.hikayeler (
    id bigint generated by default as identity primary key,
    baslik text not null default 'Kullanıcı Hikâyesi',
    metin text not null,
    dil text not null default 'tr' check (dil in ('tr', 'de', 'fr', 'ko')),
    durum text not null default 'beklemede' check (durum in ('beklemede', 'yayinda', 'reddedildi')),
    olusturma_tarihi timestamptz not null default now()
);

alter table public.hikayeler enable row level security;

drop policy if exists "Herkes hikaye gönderebilir" on public.hikayeler;
create policy "Herkes hikaye gönderebilir"
on public.hikayeler for insert
to anon, authenticated
with check (durum = 'beklemede');

drop policy if exists "Herkes yayınlanan hikayeleri okuyabilir" on public.hikayeler;
create policy "Herkes yayınlanan hikayeleri okuyabilir"
on public.hikayeler for select
to anon, authenticated
using (durum = 'yayinda');

-- Yönetici onayı Supabase Dashboard içinden yapılır:
-- beklemede -> yayinda veya reddedildi.
