-- Supabase projesi yeniden etkinleşmeden ÇALIŞTIRMAYIN. Bu yalnız gelecekteki
-- public UGC yayını için hazırlanmış migration'dır; mevcut tabloyu silmez.
alter table public.hikayeler
    add column if not exists yazar_kimligi text;

-- Mevcut yayınları koruyup yerel engelleme için benzersiz eski-yazar kimliği verin.
update public.hikayeler
set yazar_kimligi = lpad(id::text, 32, '0')
where yazar_kimligi is null;

alter table public.hikayeler
    alter column yazar_kimligi set not null;

alter table public.hikayeler
    drop constraint if exists hikayeler_baslik_uzunluk,
    drop constraint if exists hikayeler_metin_uzunluk,
    add constraint hikayeler_baslik_uzunluk check (char_length(baslik) between 1 and 80),
    add constraint hikayeler_metin_uzunluk check (char_length(metin) between 20 and 5000);

alter table public.hikayeler enable row level security;

drop policy if exists "Herkes hikaye gönderebilir" on public.hikayeler;
create policy "Herkes hikaye gönderebilir"
on public.hikayeler for insert to anon, authenticated
with check (
    durum = 'beklemede'
    and char_length(yazar_kimligi) = 32
    and char_length(baslik) between 1 and 80
    and char_length(metin) between 20 and 5000
);

drop policy if exists "Herkes yayınlanan hikayeleri okuyabilir" on public.hikayeler;
create policy "Herkes yayınlanan hikayeleri okuyabilir"
on public.hikayeler for select to anon, authenticated
using (durum = 'yayinda');

create table if not exists public.hikaye_raporlari (
    id bigint generated by default as identity primary key,
    hikaye_id bigint not null references public.hikayeler(id) on delete cascade,
    bildiren_kimlik text not null check (char_length(bildiren_kimlik) = 32),
    neden text not null check (neden in ('uygunsuz', 'taciz', 'telif', 'diger')),
    olusturma_tarihi timestamptz not null default now(),
    unique (hikaye_id, bildiren_kimlik)
);

alter table public.hikaye_raporlari enable row level security;
drop policy if exists "Anon rapor ekleyebilir" on public.hikaye_raporlari;
create policy "Anon rapor ekleyebilir"
on public.hikaye_raporlari for insert to anon, authenticated
with check (char_length(bildiren_kimlik) = 32);

-- Raporlar yalnız Supabase Dashboard'daki yetkili geliştirici tarafından okunur.
-- Her hikaye önce beklemede kalır; incelemeden sonra yayinda veya reddedildi yapılır.
-- İtirazlar uygulamadaki destek e-postası üzerinden değerlendirilir.
